import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "@/components/ui/toaster";
import { FormContext, FormProvider } from "@/context/formContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="absolute top-0 left-0 w-full px-[53px]  py-5 h-[10vh] flex justify-between ">
          <h1 className=" text-3xl uppercase font-semibold ">AssessForm</h1>
          <div className="flex gap-3">
            <Link
              className=" bg-[#0A0513] cursor-pointer text-white h-10 w-[150px] rounded-md flex justify-center items-center border "
              href="/register"
            >
              Sign Up
            </Link>
            <Link
              className=" w-[150px] h-10 cursor-pointer bg-white border-[#0A0513] rounded-md flex justify-center items-center border "
              href="/login"
            >
              Login
            </Link>
          </div>
        </div>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
